import time
print()
print("30 years after the imposing geological catastrophe")
print()
time.sleep(3)
print("The surface of the earth, still sheathed by a thick layer of ash and dust")
print()
time.sleep(4)
print("The consequences of purposeful disregardance...")
print()
print()
time.sleep(3.25)
print("Sanctuary awaits!")
print()
time.sleep(1.5)
while True:
    print("Would you like to start your adventure? (Y or N)")
    go = input()
    if go == "Y":
        print("Darkness...")
        print()
        time.sleep(2)
        print("A scorching heat radiates across you")
        time.sleep(2)
    else:
        print("false")